import {CodeHelper} from '../../helpers/CodeHelper.js';
import {HTMLHelper} from '../../helpers/HTMLHelper.js';
import {IProps, IState, DefaultProps, DefaultState, Base} from './Base.js';
import {FullStackBlend, DeclarationHelper} from '../../helpers/DeclarationHelper.js';
import {CodeGenerationHelper} from '../../helpers/CodeGenerationHelper.js';
import {CAMEL_OF_EVENTS_DICTIONARY} from '../../Constants.js';

declare let React: any;
declare let ReactDOM: any;
declare let perform: any;
declare let ts: any;
declare let zip: any;

interface Props extends IProps {
}

interface State extends IState {
   value: string,
   loading: boolean,
   requiredFilesLoaded: boolean
}

let ExtendedDefaultProps = Object.assign({}, DefaultProps);
let keys = [...Object.keys(CAMEL_OF_EVENTS_DICTIONARY)];
let watchingAttributeNames = [];
for (let name of keys) {
		watchingAttributeNames.push(name);
		watchingAttributeNames.push('internal-fsb-react-code-' + name);
}
watchingAttributeNames.push('internal-fsb-name');
watchingAttributeNames.push('internal-fsb-class');
watchingAttributeNames.push('internal-fsb-guid');
watchingAttributeNames.push('internal-fsb-react-namespace');
watchingAttributeNames.push('internal-fsb-react-class');
watchingAttributeNames.push('internal-fsb-react-id');
watchingAttributeNames.push('internal-fsb-react-mode');
watchingAttributeNames.push('internal-fsb-react-data');
watchingAttributeNames.push('internal-fsb-react-code-import');
watchingAttributeNames.push('internal-fsb-react-code-declare');
watchingAttributeNames.push('internal-fsb-react-code-interface');
watchingAttributeNames.push('internal-fsb-react-code-body');
watchingAttributeNames.push('internal-fsb-react-code-footer');

zip.workerScriptsPath = "/js/lib/";

Object.assign(ExtendedDefaultProps, {
	  watchingAttributeNames: watchingAttributeNames,
	  watchingExtensionNames: ['autoGeneratedCodeForRenderMethod', 'autoGeneratedCodeForMergingSection']
});

let ExtendedDefaultState = Object.assign({}, DefaultState);
Object.assign(ExtendedDefaultState, {
    value: '',
    loading: false,
    requiredFilesLoaded: false
});

class SitePreview extends Base<Props, State> {
		protected state: State = {};
    protected static defaultProps: Props = ExtendedDefaultProps;

    constructor(props) {
        super(props);
        Object.assign(this.state, CodeHelper.clone(ExtendedDefaultState));
    }
    
    componentDidMount() {
    		window.addEventListener("message", (event) => {
			    let data = JSON.parse(event.data);
			  	if (data.target == 'site-preview') {
			  		switch (data.name) {
			  			case 'load':
			  				this.setState({
				    			loading: data.content	
				    		});
				    		break;
			  		}
			    }
			  });
    }
    
   	requiredFiles: any = {
    		"src/public/js/helpers/CodeHelper.ts": false,
    		"src/public/js/helpers/DeclarationHelper.ts": false,
    		"src/public/js/helpers/EventHelper.ts": false,
    		"src/public/js/components/Base.tsx": false
    };
    requiredFilesRemainingCount: number = 4;
    zipReader: any = null;
    reader: any = null;
    currentKey: string = null;
    
    public update(properties: any) {
        if (!super.update(properties)) return;
    }
    
    public clear() {
    		let count = 0;
    		for (let key in this.requiredFiles) {
    				if (this.requiredFiles.hasOwnProperty(key)) {
    							this.requiredFiles[key] = false;
    							count += 1;
    				}
    		}
    		this.requiredFilesRemainingCount = count;
    		if (this.zipReader) this.zipReader.close();
    		this.zipReader = null;
    		this.reader = null;
    		this.currentKey = null;
    }
    
    public start() {
    		this.setState({
    			loading: true	
    		});
    		
    		if (!this.state.requiredFilesLoaded) {
		    		this.clear();
		    		
		    		HTMLHelper.addClass(document.body, 'internal-fsb-preview-on');
		    		
		    		var request = new XMLHttpRequest();
						request.addEventListener("load", this.unzip.bind(this, request));
						request.addEventListener("error", this.close.bind(this));
						request.responseType = 'blob';
						request.open("GET", "/boilerplate.zip");
						request.send();
				} else {
						HTMLHelper.addClass(document.body, 'internal-fsb-preview-on');
						
						this.display();
				}
    }
    
    private unzip(request) {
    		this.currentKey = null;
			  zip.createReader(new zip.BlobReader(request.response), ((zipReader) => {
			    zipReader.getEntries(((entries) => {
			    	for (let entry of entries) {
			    		if (typeof this.requiredFiles[entry.filename] === 'boolean') {
			    			this.requiredFiles[entry.filename] = entry;
			    		}
				    }
				    this.read();
			    }).bind(this));
			    this.zipReader = zipReader;
			  }).bind(this), this.close.bind(this));
    }
    
    private read() {
    		if (this.reader == null) {
    				this.reader = new FileReader();
    				this.reader.addEventListener('loadend', ((event) => {
    						if (typeof this.requiredFiles[this.currentKey] === 'object') {
				    				this.requiredFiles[this.currentKey] = event.srcElement.result;
				    				this.requiredFilesRemainingCount -= 1;
				    		}
				    		if (this.requiredFilesRemainingCount > 0) this.read();
				    		else {
				    			if (this.zipReader) this.zipReader.close();
				    			this.zipReader = null;
				    			
				    			this.state.requiredFilesLoaded = true;
				    			
				    			this.compile();
				    		}
						}).bind(this));
						this.reader.addEventListener('error', this.close.bind(this));
    		}
    		for (let key in this.requiredFiles) {
    				if (this.requiredFiles.hasOwnProperty(key)) {
    						if (typeof this.requiredFiles[key] === 'object') {
	    							this.currentKey = key;
    								let entry = this.requiredFiles[key];
	    							entry.getData(new zip.BlobWriter("text/plain", this.close.bind(this)), ((data) => {
								        this.reader.readAsText(data);
							      }).bind(this));
	    							return;
    						}
    				}
    		}
    }
    
    private compile() {
    		for (let key in this.requiredFiles) {
		        if (this.requiredFiles.hasOwnProperty(key)) {
		        		if (typeof this.requiredFiles[key] === 'string') {
										this.requiredFiles[key] = ts.transpileModule(this.requiredFiles[key], {compilerOptions: {module: ts.ModuleKind.AMD, jsx: "react"}}).outputText;
										this.requiredFiles[key] = URL.createObjectURL(new Blob([this.requiredFiles[key]]));
								}
		    		}
		    }
		    
		    this.display();
    }
    
    private display() {
    		let code, mapping;
    		if (this.state.attributeValues['internal-fsb-react-mode']) {
          	let info = this.state.attributeValues;
            info.autoGeneratedCodeForRenderMethod = this.state.extensionValues['autoGeneratedCodeForRenderMethod'];
            info.autoGeneratedCodeForMergingSection = this.state.extensionValues['autoGeneratedCodeForMergingSection'];
            
            [code, mapping] = CodeGenerationHelper.generateReactCode(info, 'Main');
        } else {
            let info = this.state.attributeValues;
            info.autoGeneratedCodeForRenderMethod = this.state.extensionValues['autoGeneratedCodeForRenderMethod'];
            info.autoGeneratedCodeForMergingSection = this.state.extensionValues['autoGeneratedCodeForMergingSection'];
            
        		[code, mapping] = CodeGenerationHelper.generateMergingCode(info, 'Main');
        }
        
        code = ts.transpileModule(code, {compilerOptions: {module: ts.ModuleKind.AMD, jsx: "react"}}).outputText;
        let url = 'data:text/javascript;charset=utf8;base64,' + CodeHelper.convertToBase64(code);
    		
        let preview = ReactDOM.findDOMNode(this.refs.preview);
        let contentWindow = preview.contentWindow || preview.contentDocument.document || preview.contentDocument;
        
				contentWindow.document.open();
				contentWindow.document.write(
`<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Untitled - Construction Area</title>
		<meta name="description" content="" />
		<link rel="stylesheet" href="/css/embed.css">
	</head>
	<body>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js"></script>
		<script type="text/typescript">
			// Load AMD modules.
			// 
			let requiredFiles = ${JSON.stringify(this.requiredFiles)};
			
			require(["https://unpkg.com/react@16/umd/react.development.js"], (React) => {
				define('react', React);
				
				require(["https://unpkg.com/react-dom@16/umd/react-dom.development.js"], (ReactDOM) => {
					window.React = React;
					window.ReactDOM = ReactDOM;
					
					require([
						requiredFiles["src/public/js/helpers/CodeHelper.ts"],
						requiredFiles["src/public/js/helpers/DeclarationHelper.ts"],
						requiredFiles["src/public/js/helpers/EventHelper.ts"]
					], (CodeHelper, DeclarationHelper, EventHelper) => {
						define('CodeHelper', CodeHelper);
						define('DeclarationHelper', DeclarationHelper);
						define('EventHelper', EventHelper);
						
						require([
							requiredFiles["src/public/js/components/Base.tsx"]
						], (Base) => {
							define('Base', Base);
							
							require(["${url}"], (Component) => {
								let container = document.createElement('div');
								ReactDOM.render(React.createElement(Component.Main, {}, null), container);
								document.body.appendChild(container);
								
								window.top.postMessage(JSON.stringify({
						    	target: 'site-preview',
						      name: 'load',
						      content: false
						    }), '*');
							});
						});
					});
				});
			});
		</script>
		<script src="https://rawgit.com/Microsoft/TypeScript/master/lib/typescriptServices.js"></script>
		<script src="https://rawgit.com/basarat/typescript-script/master/transpiler.js"></script>
		<script src="/js/Embed.bundle.js"></script>
	</body>
</html>
`);
				contentWindow.document.close();
    }
    
    private close(error) {
    		if (error instanceof Error) {
    			console.log(error.message);
    			this.clear();
    		}
    	
    		HTMLHelper.removeClass(document.body, 'internal-fsb-preview-on');
    		
    		let preview = ReactDOM.findDOMNode(this.refs.preview);
        let contentWindow = preview.contentWindow || preview.contentDocument.document || preview.contentDocument;
    		
    		contentWindow.location = 'about:blank';
    }
    
    render() {
      return pug `
      	.site-preview
      		.close-button.btn.btn-sm.btn-light.px-3(onClick=this.close.bind(this))
      			i.fa.fa-close.m-0
      		.iframe-container
      			.iframe-navigation-bar
      			.iframe-body
      				iframe(ref="preview")
      		.loading-container(style={display: this.state.loading ? 'block' : 'none'})
      			.linear-background
      				.inter-left
      				.inter-right--top
      				.inter-right--bottom
      			.linear-background
      				.inter-left
      				.inter-right--top
      				.inter-right--bottom
      			.linear-background
      				.inter-left
      				.inter-right--top
      				.inter-right--bottom
      `
    }
}

DeclarationHelper.declare('Components.SitePreview', SitePreview);

export {Props, State, SitePreview};