var BackEndDOMHelper = {
	autoGeneratedCodeForBackEndScript: function(element: HTMLElement) {
		return "// Main";
	},
	autoGeneratedCodeForMergingBackEndScript: function(element: HTMLElement) {
		return "// Merge";
	}
}

export {BackEndDOMHelper};