// Auto[Generating:V1]--->
// PLEASE DO NOT MODIFY BECAUSE YOUR CHANGES MAY BE LOST.

// Auto[Import]--->
import {Project, DeclarationHelper} from '../helpers/DeclarationHelper.js';
import {CodeHelper} from '../helpers/CodeHelper.js';
import {EventHelper} from '../helpers/EventHelper.js';
import {HTMLHelper} from '../helpers/HTMLHelper.js';
import {IBaseProps, IBaseState, DefaultBaseProps, DefaultBaseState, Base} from './Base.js';
// <---Auto[Import]

// Import additional modules here:
//

// Auto[Declare]--->

declare let React: any;
declare let ReactDOM: any;
declare let window: any;
declare let DataManipulationHelper: any;

// <---Auto[Declare]

// Declare private static variables here:
//

// Auto[Interface]--->
interface IAutoBaseProps extends IBaseProps {
  forward: {classes: String, styles: any};
}
interface IAutoBaseState extends IBaseState {
}
// <---Auto[Interface]

// Declare or extend interfaces here:
//
interface IProps extends IAutoBaseProps {
  
}
interface IState extends IAutoBaseState { 
}

let DefaultProps = Object.assign({}, DefaultBaseProps, {
  
});
let DefaultState = Object.assign({}, DefaultBaseState, {
  
});

// Auto[ClassBegin]--->
class FlowLayout_0a9730e3 extends Base {
  state: IState = null;
  protected static defaultProps: IProps = DefaultProps;
  
  constructor(props) {
    super(props);
    this.state = CodeHelper.clone(DefaultState);
    
    this.initialize();
  }
  
  register() {

  }
  // <---Auto[ClassBegin]
  
  // Declare class variables and functions here:
  //
  protected initialize(): void {
  }
  
  protected componentDidMount(): void {
  	this.register();
  }
  
  protected componentWillUnmount(): void {
  }
  
  // Providing data array base on dot notation:
  // 
  protected getDataFromNotation(notation: string, inArray: boolean=false): any {
    return super.getDataFromNotation(notation, inArray);
  }
  
  // Auto[Merging]--->
  // <---Auto[Merging]
  
  // Auto[ClassEnd]--->
  protected render(): any {
    return (
      <div className={"internal-fsb-element col-12 " + (this.props.forward && this.props.forward.classes || '')} internal-fsb-guid="0a9730e3" style={Object.assign({}, this.props.forward && this.props.forward.styles || {})}>
        <div className="container-fluid">
          <div className="row internal-fsb-strict-layout internal-fsb-allow-cursor">
            <div className="internal-fsb-element col-12 -fsb-preset-08abd2c9" internal-fsb-guid="0522150b" style={{'FsbInheritedPresets': '08abd2c9'}} dangerouslySetInnerHTML={{__html: CodeHelper.escape(this.getDataFromNotation("Log.message"))}}></div>
            <div className="internal-fsb-element -fsb-preset-08abd2c9 col-12 offset-0" internal-fsb-guid="c4382c32" style={{'FsbInheritedPresets': '08abd2c9', 'transform': 'matrix3d(1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1)scaleY(-1)', 'WebkitTransform': 'matrix3d(1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1)scaleY(-1)', 'MozTransform': 'matrix3d(1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1)scaleY(-1)', 'MsTransform': 'matrix3d(1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1)scaleY(-1)'}}>
              <div>
                This StackBlend platform is an editor for website development enthusiasts, not only for full-stack engineers, who want to develop a web application using the latest open source technologies based on JavaScript language. The StackBlend will help you cope with front-end, back-end, UI/UX, and content in a single one editor. You may design the user interface right from the editor, configure their properties and data dot notations, link them to fully customizable server-side scripts, and get the results back on the client-side using less than 10 lines of code, where the rests are auto-generated by the editor.
                <br />
              </div>
              <div>
                <br />
              </div>
              <div>
                Since the platform is underdevelopment, we suggest that when you found P0-P1 errors and even technical issues which prevent you from achieving what you intend to develop, please send an email to jatupon@softenstorm.com and indicating 1.) what you want to do? 2.) what are bugs and errors happened in the developer console? 3.) where is it or provide any screenshot? We will promptly answer those issues about their workarounds and details of upcoming hotfixes. We will also let you know other workarounds by posting them on this page, too.
              </div>
              <div>
                <br />
              </div>
              <div>
                Last but not least, keep saving and opening a developer console to see what's going wrong in the background. If you have found or being struck on any unusable instruction, don't hesitate to send an email to jatupon@softenstorm.com.
              </div>
            </div>
            <Project.Controls.TextElement_bb6cddae />
            <Project.Controls.TextElement_b19840c8 />
            <Project.Controls.TextElement_92de9e1b />
            <div className="internal-fsb-element -fsb-preset-08abd2c9 -fsb-self-a43dc1c9 col-12 offset-0" internal-fsb-guid="a43dc1c9">
              Current Investigating Issues / Underdevelopment Features:
              <div>
                <br />
              </div>
              <div>
                1. Services Exploration
              </div>
              <div>
                2. Graphics & WebGL Element Insertion
              </div>
              <div>
                3. Scheduler, Route, and Event of Data Flows Designing
              </div>
            </div>
            <div className="internal-fsb-element -fsb-preset-a43dc1c9 col-12 offset-0" internal-fsb-guid="2135749e" style={{'FsbInheritedPresets': 'a43dc1c9'}}>
              Workarounds:
              <div>
                <br />
              </div>
              <div>
                1. Silence of Save/Merge/Deploy: solve by waiting for 5-15 seconds, if you can't wait, watch what are going on from networks tab of the developer console.
              </div>
              <div>
                2. Undo/Redo Not Working Sometime: keep saving and reload the editor.
              </div>
              <div>
                3. Unable to Merge/Deploy: resolve the conflicts manually using a terminal on your operating system, or go to GitHub to perform it.
              </div>
              <div>
                4. Silence of Automatic Deploy: go to Heroku.com and see if it's deploying or losing the hooks.
              </div>
              <div>
                5.Failed of Automatic Deploy: clone the project into your local machine and debug it using "npm run build", then try to change the code on StackBlend based on the errors, re-save, run "git reset --hard && git pull", and run "npm run build" to see if it fixed.
              </div>
            </div>
            <Project.Controls.TextElement_738cbdce />
            <div className="internal-fsb-element col-12 -fsb-preset-08abd2c9" internal-fsb-guid="2d9c731e" style={{'FsbInheritedPresets': '08abd2c9', 'textAlign': 'center'}}>
              ©2020 by SoftenStorm 
            </div>
          </div>
        </div>
      </div>
    )
  }
}
DeclarationHelper.declare('Document', 'Controls.FlowLayout_0a9730e3', FlowLayout_0a9730e3);
// <---Auto[ClassEnd]

// Export variables here:
//
export {IProps, IState, DefaultProps, DefaultState};

// <--- Auto[Generating:V1]
// PLEASE DO NOT MODIFY BECAUSE YOUR CHANGES MAY BE LOST.